/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "inverse-on-surface": "#f1effa",
        "on-surface-variant": "#4c4546",
        "surface-dim": "#dad9e3",
        "on-secondary-fixed": "#221b00",
        "surface-container-low": "#f4f2fd",
        "on-background": "#1a1b22",
        "on-tertiary": "#ffffff",
        "primary": "#000000",
        "surface-container-high": "#e8e7f1",
        "on-error": "#ffffff",
        "surface": "#fbf8ff",
        "surface-tint": "#5e5e5e",
        "secondary-fixed-dim": "#e9c400",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#1a1c1d",
        "on-tertiary-fixed-variant": "#454748",
        "tertiary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#ffe16d",
        "surface-container": "#eeedf7",
        "outline": "#7e7576",
        "inverse-primary": "#c6c6c6",
        "primary-fixed-dim": "#c6c6c6",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6e5c00",
        "surface-container-highest": "#e3e1ec",
        "tertiary-container": "#1a1c1d",
        "outline-variant": "#cfc4c5",
        "surface-bright": "#fbf8ff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "background": "#fbf8ff",
        "primary-fixed": "#e2e2e2",
        "on-primary-fixed-variant": "#474747",
        "on-error-container": "#93000a",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "secondary": "#705d00",
        "on-tertiary-container": "#838485",
        "tertiary-fixed": "#e2e2e3",
        "tertiary": "#000000",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#544600",
        "on-surface": "#1a1b22",
        "surface-variant": "#e3e1ec",
        "secondary-container": "#fcd400",
        "inverse-surface": "#2f3038",
        "on-primary-fixed": "#1b1b1b"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sm": "12px",
        "base": "8px",
        "xs": "4px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "grid-pattern": "20px"
      },
      "fontFamily": {
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"]
      },
      "fontSize": {
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
